
name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: final_db
          POSTGRES_USER: final_user
          POSTGRES_PASSWORD: final_pass
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U final_user; do
            echo "Waiting for postgres..."
            sleep 1
          done

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          pytest
        env:
          DB_HOST: localhost
          DB_NAME: final_db
          DB_USER: final_user
          DB_PASSWORD: final_pass
